apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eks-fluentd-s3.fullname" . }} 
  labels: {{ include "eks-fluentd-s3.labels" . | nindent 4 }}
data:
  S3_BUCKET_NAME: "{{ .Values.s3.bucket_name }}"
  S3_BUCKET_PREFIX: "{{ .Values.s3.bucket_prefix }}"
  S3_BUCKET_REGION: "{{ .Values.s3.region }}"
  AWS_REGION: "{{ .Values.s3.region }}"
  # EKS provides the token file & role ARN from the service account
  AWS_ROLE_SESSION_NAME: "{{ .Values.s3.role_session_name }}"
  FLUENTD_PROMETHEUS_BIND: "{{ .Values.prometheus.bind }}"
  FLUENTD_PROMETHEUS_PORT: "{{ .Values.prometheus.port }}"
  FLUENTD_PROMETHEUS_PATH: "{{ .Values.prometheus.path }}"
  FLUENT_CONTAINER_TAIL_PARSER_TYPE: "{{ .Values.k8s.parser_type }}"
  FLUENT_FILTER_KUBERNETES_URL: "{{ .Values.k8s.api_url }}"
  KUBERNETES_VERIFY_SSL: "{{ .Values.k8s.verify_ssl }}"
  KUBERNETES_CA_FILE: "{{ .Values.k8s.ca_file }}"
