apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "eks-fluentd-s3.fullname" . }}
  labels: {{ include "eks-fluentd-s3.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "eks-fluentd-s3.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "eks-fluentd-s3.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "eks-fluentd-s3.fullname" . }}
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
{{- if .Values.tolerations }}
{{ .Values.tolerations | toYaml | indent 6 }}
{{- end }}
      containers:
      - name: {{ template "eks-fluentd-s3.fullname" . }}
        image: {{ .Values.fluent_image }} 
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: {{ template "eks-fluentd-s3.fullname" . }}
        args:
        - --use-v1-config
        ports:
        - name: metrics
          containerPort: {{ .Values.prometheus.port }}
        resources: {{ .Values.resources | toYaml | nindent 10 }}
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
