apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "eks-fluentd-s3.fullname" . }} 
  labels:
    app: {{ template "eks-fluentd-s3.fullname" . }} 
    chart: {{ template "eks-fluentd-s3.chart" . }} 
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.s3.role_arn }}"
