apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "eks-fluentd-s3.fullname" . }} 
  labels: {{ include "eks-fluentd-s3.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.s3.role_arn }}"
