s3:
  bucket_name: debug
  bucket_prefix: ''
  region: us-west-2
  role_session_name: 'eks-fluentd-s3'
  role_arn: ''
prometheus:
  bind: '0.0.0.0'
  port: '24231'
  path: '/metrics'
  service_monitor:
    enabled: false
    interval: 10s
    scrape_timeout: 6s
    namespace: prometheus
k8s:
  parser_type: 'json'
  api_url: ''
  verify_ssl: 'true'
  ca_file: ''
fluent_image: 'gomothership/eks-fluentd-s3:latest'
