apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "eks-fluentd-s3-chart.fullname" . }}
  labels:
    k8s-app: {{ template "eks-fluentd-s3-chart.fullname" . }}
    chart: {{ template "eks-fluentd-s3-chart.chart" . }} 
spec:
  template:
    metadata:
      labels:
        app: {{ template "eks-fluentd-s3-chart.fullname" . }}
    spec:
      serviceAccountName: {{ template "eks-fluentd-s3-chart.fullname" . }}
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: {{ template "eks-fluentd-s3-chart.fullname" . }}
        image: {{ .Values.fluent_image }} 
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: {{ template "eks-fluentd-s3-chart.fullname" . }}
        args:
        - --use-v1-config
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
